services:
  app:
  db:
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass1234
      - MYSQL_DATABASE=sample
      - TZ=Asia/Tokyo
    volumes:
  mail:
    environment:
      - TZ=Asia/Tokyo
      - MP_DATA_FILE=/data/mailpit.db
